version: 2

common_cache_key: &common_cache_key
  key: dependency-cache-{{ checksum "../ocaml-version" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "hpack.opam" }}-{{ checksum "http2af.opam" }}-{{ checksum "http2af-lwt.opam" }}-{{ checksum "http2af-lwt-unix.opam" }}-{{ checksum "http2af-mirage.opam" }}

esy_cache_key: &esy_cache_key
  key: esy-cache-{{ checksum "esy.json" }}-{{ checksum "../esy-checksum" }}-{{ checksum ".circleci/config.yml" }}

esy_post_build_cache_key: &esy_post_build_cache_key
  key: esy-post-build-cache-{{ checksum "esy.json" }}-{{ checksum "../esy-checksum" }}-{{ checksum ".circleci/config.yml" }}

spec-steps: &spec-steps
  name: 'Conformance tests'
  command: |
    curl -L https://github.com/summerwind/h2spec/releases/download/v2.2.1/h2spec_linux_amd64.tar.gz | tar xvz
    nohup dune exec spec/lwt_h2spec_string.exe &
    ./h2spec --strict -p 8080
    kill $(lsof -i tcp:8080 | awk '{print $2}' | grep -v PID)

    nohup dune exec spec/lwt_h2spec_bigstring.exe &
    ./h2spec --strict -p 8080
    kill $(lsof -i tcp:8080 | awk '{print $2}' | grep -v PID)

    nohup dune exec spec/lwt_h2spec_streaming.exe &
    ./h2spec --strict -p 8080 --timeout 3
    kill $(lsof -i tcp:8080 | awk '{print $2}' | grep -v PID)

opam-steps: &opam-steps
  steps:
    - checkout
    - run:
        name: "Pull Submodules"
        command: git submodule update --init --recursive
    - run:
        name: "Note OCAML_VERSION for cache"
        command: echo $OCAML_VERSION > ../ocaml-version
    - restore_cache:
        <<: *common_cache_key
    - run:
        name: "Initialize opam"
        command: |
          sudo apt-get install -y m4
          opam init --auto-setup --dot-profile=~/.bash_profile
          opam remote add ocamlorg https://opam.ocaml.org || true
          opam remote remove default || true
    - run:
        name: "Install deps"
        command: |
          sudo apt-get install -y pkg-config libgmp-dev autotools-dev autoconf
          opam update
          opam install -y dune
          opam install -t --deps-only .
    - run:
        name: 'Clean'
        command: rm -rf ./_build
    - save_cache:
        <<: *common_cache_key
        paths:
          - ~/.opam
    - run:
        name: 'Test'
        command: |
          source ~/.bash_profile
          eval `opam config env`
          dune build @all
          dune runtest --no-buffer
          dune build @slowtests --no-buffer
    - run:
        <<: *spec-steps
    - run:
        name: 'Check git is clean'
        command: git diff --exit-code

jobs:
  4.04.2:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.04
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.04.2"
    <<: *opam-steps
  4.05.0:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.05
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.05.0"
    <<: *opam-steps
  4.06.1:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.06
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.06.1"
    <<: *opam-steps
  4.07.1:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.07
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.07.1"
    <<: *opam-steps
  esy:
    docker:
      - image: circleci/node:11.9
    environment:
      - TERM: dumb
      - NPM_CONFIG_PREFIX: "~/.npm-global"
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: git submodule update --init --recursive
      - run:
          name: 'Note esy.lock checksum for cache'
          command: find esy.lock -type f -exec md5sum {} \; | sort -k 2 | md5sum > ../esy-checksum
      - restore_cache:
          <<: *esy_cache_key
      - restore_cache:
          <<: *esy_post_build_cache_key
      - run:
          name: "Install esy + system deps"
          command: |
            sudo apt-get install texinfo
            npm install -g esy
      - run:
          name: 'esy install'
          command: ~/.npm-global/bin/esy install
      - save_cache:
          <<: *esy_cache_key
          paths:
            - ~/.npm-global
            - ~/.esy
            - node_modules
            - _esy
      - run:
          name: 'esy build'
          command: ~/.npm-global/bin/esy b dune build @all
      - run:
          name: 'esy test'
          command: ~/.npm-global/bin/esy b dune runtest --no-buffer
      - run:
          name: 'esy slow-test'
          command: ~/.npm-global/bin/esy b dune build @slowtests --no-buffer
      - run:
          <<: *spec-steps
      # Use both pre and post build caches so that we're more likely
      # to have dependencies cached. `esy build` is more likely to fail,
      # so this will make the push that fixes the build faster
      - save_cache:
          <<: *esy_post_build_cache_key
          paths:
            - ~/.esy
            - node_modules
            - _esy

workflows:
  version: 2
  build-deploy:
    jobs:
      - 4.04.2
      - 4.05.0
      - 4.06.1
      - 4.07.1
      - esy
